name: Continuous Integration

on:
  workflow_call:
    inputs: 
      java_version:
        description: "Supports an exact version or a version range using SemVer notation (if supported by Java distribution)"
        required: false
        default: 8
        type: number
      java_distribution:
        description: "Java distribution."
        required: false
        default: 'corretto'
        type: string
      skip_tests:
        description: "Used to temporarily skip the test stage"
        required: false
        type: boolean
        default: false
      maven_deploy_cmd:
        description: "Maven deploy command."
        required: false
        default: 'mvn -DupdateReleaseInfo=true jar:jar deploy:deploy'
        type: string

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
env:
  SKIP_RELEASE: ${{ contains(github.event.head_commit.message, 'release skip') || contains(github.event.head_commit.message, 'skip release') }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build and Test
    env:
      MAVEN_CLI_OPTS: "--batch-mode --show-version --errors"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Switch HEAD
        env:
          GIT_HEAD: ${{ github.event.pull_request.head.sha }}
        run: |
          echo $GIT_HEAD
          echo $GITHUB_SHA
          [ ! -z "$GIT_HEAD" ] && git checkout $GIT_HEAD
          echo $(git rev-parse --short=9 HEAD)

      - name: Prepare Release
        if: ${{ github.ref == 'refs/heads/master' && env.SKIP_RELEASE != true }}
        run: |
          git config user.name "GitHub Actions build"
          git config user.email ${{ secrets.BUILD_USER_EMAIL }}
          npx commit-and-tag-version --tag-prefix=''

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}
          architecture: x64
          cache: 'maven'

      - name: Set groupId for branch
        if: ${{ github.ref != 'refs/heads/master' }}
        env:
          GIT_BRANCH_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "GIT_BRANCH_REF=$GIT_BRANCH_REF"
          BRANCH_NAME=$(echo $GIT_BRANCH_REF | sed -e 's/[\/]/./g' | sed -e 's/[^-a-zA-Z0-9._]/-/g')
          BASE_GROUP_ID="com.klipfolio"
          BRANCH_GROUP_ID="$BASE_GROUP_ID.branch.$BRANCH_NAME"
          sed -i "0,/${BASE_GROUP_ID}/s/${BASE_GROUP_ID}/${BRANCH_GROUP_ID}/" pom.xml

      - name: Set version
        run: |
          VERSION=$(cat manifest.json | jq -r .version)
          VERSION_WITH_SHA=$VERSION-$(git rev-parse --short=9 HEAD)
          if [[ $GITHUB_REF != "refs/heads/master" ]]; then
            VERSION=$VERSION_WITH_SHA
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_WITH_SHA=$VERSION_WITH_SHA" >> $GITHUB_ENV

      - name: Prepare Maven settings
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_WRITE_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_WRITE_PASSWORD }}
          NEXUS_REPO_URL: ${{ secrets.NEXUS_REPO_URL }}
        run: |
          curl --silent ${{ vars.MAVEN_CONFIG_TEMPLATE_URL }} \
          --output ./maven_config_template.sh && \
          chmod u+x ./maven_config_template.sh && \
          ./maven_config_template.sh > ~/.m2/settings.xml

          mvn versions:set -DnewVersion=$VERSION

      - name: Compile
        run: mvn clean compile
      
      - name: Test
        if: ${{ ! inputs.skip_tests }}
        id: unit-tests
        run: mvn jacoco:prepare-agent resources:testResources compiler:testCompile surefire:test jacoco:report

      - name: Create Unit Test Report
        if: steps.unit-tests.outcome == 'failure'
        run: |
          mvn surefire-report:report-only

      - name: Upload unit test report
        if: steps.unit-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report.html
          path: target/site/surefire-report.html

      - name: Deploy
        run: |
          sudo chown -R $USER:$USER "$HOME/.m2/repository"
          ${{ inputs.maven_deploy_cmd }}

      - name: Release
        if: ${{ github.ref == 'refs/heads/master' && env.SKIP_RELEASE != true }}
        env:
          COMMIT_KEY: ${{ secrets.COMMIT_KEY }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          # Remove default token (read-only)
          git config --unset http.https://github.com/.extraheader
          # Setup ssh access
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${COMMIT_KEY}"
          git config --add url.git@github.com:.insteadof https://github.com/
          # Push release commit
          git push --follow-tags origin master

      - name: Checkout actions repo
        if: ${{ failure() && github.ref == 'refs/heads/master' }}
        uses: actions/checkout@v4
        with:
          repository: Klipfolio/kf-github-actions
          path: kf-github-actions
          token: ${{ secrets.PA_GITHUB_REPO_ACCESS }}

      - name: Slack Notify
        if: ${{ failure() && github.ref == 'refs/heads/master' }}
        uses: ./kf-github-actions/.github/actions/slack-notify
        with:
          job_name: Build and Test
          always_notify_channel_webhook_url: ${{ secrets.SLACK_WEBHOOK_CICD_STATUS_URL }}
