name: "PR Lint"

on:
  workflow_call:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic_pull_request:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      # https://github.com/amannn/action-semantic-pull-request
      - uses: amannn/action-semantic-pull-request@47b15d52c5c30e94a17ec87eb8dd51ff5221fed9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
